wallpaper {
    monitor = HDMI-A-3
    path = /home/lumbrjx/Documents/stocks/wall.jpg
    fit_mode = cover
}

# Fallback for any other / future monitor
wallpaper {
    monitor =
    path = /home/lumbrjx/Documents/stocks/wall.jpg
    fit_mode = cover
}

splash = false
ipc = off
